name: Generate UML Diagrams

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz
          pip install pylint

      - name: Install Pyreverse
        run: pip install pylint

      - name: Generate UML diagrams
        run: pyreverse -o png -ASmy workflow_template.py

      - name: Upload UML diagrams
        uses: actions/upload-artifact@v2
        with:
          name: uml-diagrams
          path: uml-diagrams.png
